{
 "title": "Качество контейнера безопасности",
 "tags": [
  "quality",
  "security-channel"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Доступность приложения",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "container_up", "legendFormat": "container_up" }
   ]
  },
  {
   "title": "Решения контейнера",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "processed_records_total", "legendFormat": "Всего записей" },
    { "expr": "allow_total", "legendFormat": "Разрешено" },
    { "expr": "block_total", "legendFormat": "Заблокировано" }
   ]
  },
  {
   "title": "Ошибки обработки",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "processing_errors_total", "legendFormat": "Ошибки" }
   ]
  },
  {
   "title": "Время обработки",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "response_time_seconds", "legendFormat": "Время обработки" }
   ]
  }
 ]
}